"""
Module: company.core.constants
Purpose: Schema and table name constants for the company module.
         All DB objects live in the company schema; views and functions
         generated by the toolkit builder live in the toolkit schema.
"""

COMPANY_SCHEMA = "company"

# Toolkit-generated view/function prefixes (always in toolkit schema)
TABLE_TRANSLATION = "company_translation"
TABLE_BRANDS      = "company_brands"
TABLE_SECTORS     = "company_sectors"
